---
name: "Update openresty deps"

on:
  push:
    branches: [main, dev]
    paths:
      - ".github/workflows/update-openresty-deps.yml"
      - "openresty/scripts/update-deps.sh"
      - "openresty/**/Dockerfile"
  pull_request:
    paths:
      - ".github/workflows/update-openresty-deps.yml"
      - "openresty/scripts/update-deps.sh"
      - "openresty/**/Dockerfile"
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  WORK_DIR: openresty/scripts

jobs:
  check:
    name: "Update openresty deps"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7
        with:
          ref: dev

      - name: "Update dependencies"
        working-directory: ${{ env.WORK_DIR }}
        run: bash update-deps.sh

      - name: "Verify changed files"
        id: changed
        uses: tj-actions/verify-changed-files@v20

      - name: "Generate commit message"
        if: steps.changed.outputs.files_changed == 'true'
        id: commit
        working-directory: ${{ env.WORK_DIR }}
        run: |
          {
            echo "message<<EOF"
            perl ./gen-commit-msg.pl
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: "Upload commit to repository"
        if: steps.changed.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: |
            chore: bump openresty dependencies by github actions

            ${{ steps.commit.outputs.message }}
          commit_options: "--no-verify --signoff"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
